services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: polylog-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: polylog
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - polylog-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: polylog-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - polylog-network

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: polylog-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - redis
    networks:
      - polylog-network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polylog-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - polylog-network

  # MongoDB Express (Optional - for MongoDB management)
  mongo-express:
    image: mongo-express:latest
    container_name: polylog-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - polylog-network

volumes:
  mongodb_data:
  mongodb_config:
  redis_data:

networks:
  polylog-network:
    driver: bridge
